// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmCR9LP9jiu5ot2ugwgrn_DHl_RWRBPkE',
    appId: '1:901782544600:web:a2a815046e3f5396c037ad',
    messagingSenderId: '901782544600',
    projectId: 'quanlynhatro-115d6',
    authDomain: 'quanlynhatro-115d6.firebaseapp.com',
    storageBucket: 'quanlynhatro-115d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIr-dXkRPTMyxfK0RJkAoJXoDOT9Q8rs0',
    appId: '1:901782544600:android:158b0161e6ab3df2c037ad',
    messagingSenderId: '901782544600',
    projectId: 'quanlynhatro-115d6',
    storageBucket: 'quanlynhatro-115d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUe5lojwm41scZX9YJL9rnljvDAkd3Ug',
    appId: '1:901782544600:ios:be845c12ae0bdd4dc037ad',
    messagingSenderId: '901782544600',
    projectId: 'quanlynhatro-115d6',
    storageBucket: 'quanlynhatro-115d6.firebasestorage.app',
    iosBundleId: 'com.example.roomRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgUe5lojwm41scZX9YJL9rnljvDAkd3Ug',
    appId: '1:901782544600:ios:be845c12ae0bdd4dc037ad',
    messagingSenderId: '901782544600',
    projectId: 'quanlynhatro-115d6',
    storageBucket: 'quanlynhatro-115d6.firebasestorage.app',
    iosBundleId: 'com.example.roomRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmCR9LP9jiu5ot2ugwgrn_DHl_RWRBPkE',
    appId: '1:901782544600:web:b7032a48579a1a6ac037ad',
    messagingSenderId: '901782544600',
    projectId: 'quanlynhatro-115d6',
    authDomain: 'quanlynhatro-115d6.firebaseapp.com',
    storageBucket: 'quanlynhatro-115d6.firebasestorage.app',
  );
}
